# Generated by Django 4.2.7 on 2025-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_deadline_meeting_status_meeting_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
